version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    command: >
      sh -c "chown -R www-data:www-data /var/www/html/storage /var/www/html/database /var/www/html/bootstrap/cache && php-fpm"
    networks:
      - task_manager

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - task_manager

networks:
  task_manager:
    driver: bridge
